version: '3.0'
services:
  db:
    image: postgres:12
    ports:
      - "3310:5432"
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_USER: "challenge"
      POSTGRES_DB: "django_challenge"
