version: '3.8'

services:
  app:
    image: breno09/django-challenge-001_app
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "3311:5432"
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_USER: "challenge"
      POSTGRES_DB: "django_challenge"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
