# Generated by Django 4.0.4 on 2022-04-25 22:13

from django.db import migrations, models
import django.db.models.deletion
import my_challenge.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('picture', models.ImageField(blank=True, upload_to=my_challenge.models.upload_image)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, max_length=350)),
                ('first_paragraph', models.TextField(blank=True, max_length=550)),
                ('body', models.TextField(blank=True, max_length=900)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_challenge.author')),
            ],
        ),
    ]
