# Generated by Django 4.0.4 on 2022-05-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_challenge', '0002_alter_article_body_alter_article_first_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
