# Generated by Django 4.0.4 on 2022-04-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_challenge', '0002_alter_author_author_alter_author_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='firstParagraph',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
